version: 1.0.{build}
os:
- Windows Server 2012 R2
environment:
  matrix:
  - solution_name: Basic/DotNet/DotNet.sln
configuration:
  - Debug
  - Release
platform:
  - Any CPU
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - msbuild %solution_name%
  - mvn clean package --batch-mode -DskipTest -f Basic/Java/pom.xml
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2