# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: pwd
  displayName: 'Run a one-line script'


# Download Secure File
# Download a secure file to a temporary location on the build or release agent
- task: DownloadSecureFile@1
  inputs:
    secureFile: config.ini


# Copy Files
# Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    contents: config.ini
    targetFolder: '$(Build.SourcesDirectory)/basic_samples/SDS/Python/SDSPy/Python2/'
    #cleanTargetFolder: false # Optional
    overWrite: true # Optional
    #flattenFolders: false # Optional
  displayName: copy file

  
- script: cat config.ini 
  workingDirectory: $(Build.SourcesDirectory)/basic_samples/SDS/Python/SDSPy/Python2/
  displayName: display config file

- script: |
    python -m pip install --upgrade pip
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install unittest-xml-reporting    
    pip install pytest
    pip install pytest-cov
  displayName: 'Install tools'
  workingDirectory: $(Build.SourcesDirectory)/basic_samples/SDS/Python/SDSPy/Python2/
  

- script: |
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'
    
