# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


  
jobs:      
- job: DataviewJava

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :

    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: config.properties

      #
    - script: mvn install -f pom.xml 
      workingDirectory: $(Build.SourcesDirectory)/library_samples/Java/ocs_sample_library_preview/
      displayName: install library

    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: config.properties
        targetFolder: '$(Build.SourcesDirectory)/basic_samples/Dataviews/Java/dataviewjava/'
        #cleanTargetFolder: false # Optional
        overWrite: true # Optional
        #flattenFolders: false # Optional
      displayName: copy file

    - script: dir
      workingDirectory: $(Build.SourcesDirectory)/basic_samples/Dataviews/Java/dataviewjava/
      displayName: display files

      
    - script: cat config.properties 
      workingDirectory: $(Build.SourcesDirectory)/basic_samples/Dataviews/Java/dataviewjava/
      displayName: display config file
      
    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/basic_samples/Dataviews/Java/dataviewjava/pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'test'
    
