# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


  
jobs:      


- job: OMF_APIDotNet
  pool:
    name: 00-OSIManaged-Build
  steps :
    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: prod_onprem_omf_appsettings.json


    # Copy Files basic_samples\OMF_API\CSharp\OMF_API
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: prod_onprem_omf_appsettings.json
        targetFolder: '$(Build.SourcesDirectory)/omf_samples/basic_samples/OMF_API/CSharp/OMF_API/'
        #cleanTargetFolder: false # Optional  
        overWrite: true # Optional
        #flattenFolders: false # Optional 
      displayName: copy file

    - script: |
        del appsettings.json
      workingDirectory:  '$(Build.SourcesDirectory)/omf_samples/basic_samples/OMF_API/CSharp/OMF_API/'
      displayName: 'rename config file1'


    - script: |
        rename prod_onprem_omf_appsettings.json appsettings.json
      workingDirectory: $(Build.SourcesDirectory)/omf_samples/basic_samples/OMF_API/CSharp/OMF_API/
      displayName: 'rename config file'     

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: 'omf_samples/basic_samples/OMF_API/CSharp/OMF_API/OMF_API.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test

        
    - script: |
        dotnet restore
        dotnet test
      workingDirectory: $(Build.SourcesDirectory)/omf_samples/basic_samples/OMF_API/CSharp/OMF_APITests/
      displayName: 'Run Test'

    