site_name: Qi Docs
site_description: Documenation for the Qi service
#site_favicon: '/img/qidocs_favicon.ico'
copyright: Copyright &copy; 2015, OSIsoft, LLC
docs_dir: docs
#repo_url: https://github.com/chad-at-osisoft/Qi-docs-md
theme: readthedocs

pages:
- Why Qi?: 'Why-Qi.md'
- Data behavior: 'Qi-Data-Behavior.md'
- Markdown cheatsheet: 'index.md'
- Samples: 
  - 'Overview': 'samples/index.md'
  - '.Net client': 'samples/dotNetClient.md'
