#some tips: http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
site_name: Qi Docs
site_description: Documenation for the Qi service
site_favicon: '/img/qi-docs-favicon.ico'
copyright: Copyright &copy; 2015, OSIsoft, LLC
docs_dir: docs
repo_url: https://github.com/chad-at-osisoft/Qi-docs
theme: readthedocs

pages:
- Introduction: 'index.md'
- Why Qi?: 'Why-Qi.md'
- Data behavior: 'Qi-Data-Behavior.md'
- Markdown cheatsheet: 'markdown-cheatsheet.md'
- Samples: 
  - 'Overview': 'samples/index.md'
  - '.Net client': 'samples/dotNetClient.md'
  - 'Python client': 'samples/python.md'
