//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RestSampleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RestSampleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSample.RestSampleStrings", typeof(RestSampleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qi/{0}/{1}/Behaviors.
        /// </summary>
        internal static string BehaviorsBaseUrl {
            get {
                return ResourceManager.GetString("BehaviorsBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0} with Id = {1}.
        /// </summary>
        internal static string CreateErrorTemplate {
            get {
                return ResourceManager.GetString("CreateErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Qi resource {0}.
        /// </summary>
        internal static string CreateObjectErrorTemplate {
            get {
                return ResourceManager.GetString("CreateObjectErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete event from stream {0} with index = {1}.
        /// </summary>
        internal static string DeleteErrorTemplate {
            get {
                return ResourceManager.GetString("DeleteErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete events from stream {0} with indices {1}.
        /// </summary>
        internal static string DeleteMulitpleErrorTemplate {
            get {
                return ResourceManager.GetString("DeleteMulitpleErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete Qi resource {0}.
        /// </summary>
        internal static string DeleteObjectErrorTemplate {
            get {
                return ResourceManager.GetString("DeleteObjectErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/GetRangeValues?startIndex={0}&amp;skip={1}&amp;count={2}&amp;reversed={3}&amp;boundaryType={4}.
        /// </summary>
        internal static string GetRangeValuesUrlTemplate {
            get {
                return ResourceManager.GetString("GetRangeValuesUrlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/GetWindowValues?startIndex={0}&amp;endIndex={1}.
        /// </summary>
        internal static string GetWindowValuesUrlTemplate {
            get {
                return ResourceManager.GetString("GetWindowValuesUrlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/InsertValues.
        /// </summary>
        internal static string InsertMultipleBaseUrl {
            get {
                return ResourceManager.GetString("InsertMultipleBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/InsertValue.
        /// </summary>
        internal static string InsertSingleBaseUrl {
            get {
                return ResourceManager.GetString("InsertSingleBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qi/{0}/Namespaces.
        /// </summary>
        internal static string NamespacesBaseUrl {
            get {
                return ResourceManager.GetString("NamespacesBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}/Data/RemoveWindowValues?startIndex={1}&amp;endIndex={2}.
        /// </summary>
        internal static string RemoveMultipleUrlTemplate {
            get {
                return ResourceManager.GetString("RemoveMultipleUrlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}/Data/RemoveValue?index={1}.
        /// </summary>
        internal static string RemoveSingleUrlTemplate {
            get {
                return ResourceManager.GetString("RemoveSingleUrlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qi/{0}/{1}/Streams.
        /// </summary>
        internal static string StreamsBaseUrl {
            get {
                return ResourceManager.GetString("StreamsBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qi/{0}/{1}/Types.
        /// </summary>
        internal static string TypesBaseUrl {
            get {
                return ResourceManager.GetString("TypesBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0} with Id = {1}.
        /// </summary>
        internal static string UpdateErrorTemplate {
            get {
                return ResourceManager.GetString("UpdateErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/UpdateValues.
        /// </summary>
        internal static string UpdateMultipleBaseUrl {
            get {
                return ResourceManager.GetString("UpdateMultipleBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Qi resource {0}.
        /// </summary>
        internal static string UpdateObjectErrorTemplate {
            get {
                return ResourceManager.GetString("UpdateObjectErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/UpdateValue.
        /// </summary>
        internal static string UpdateSingleBaseUrl {
            get {
                return ResourceManager.GetString("UpdateSingleBaseUrl", resourceCulture);
            }
        }
    }
}
