parameters:
  secrets: ''
  appsettings: 'appsettings.json'
  placeholder: 'appsettings.placeholder.json'

steps:
  # Remove any appsettings from previous runs
  - powershell: Get-ChildItem -Recurse ${{ parameters.appsettings }} | Remove-Item
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Remove any existing ${{ parameters.appsettings }} files'

  # Rename Secure File
  - powershell: Get-ChildItem -Recurse ${{ parameters.placeholder }} | Rename-Item -NewName ${{ parameters.appsettings }}
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Rename ${{ parameters.placeholder }} to ${{ parameters.appsettings }}'

  # Download secrets from Azure Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: '$(azureSubscription)'
      KeyVaultName: 'Github-Samples'
      SecretsFilter: ${{ parameters.secrets }}
      RunAsPreJob: false
    condition: ne('${{ parameters.secrets }}', '')

  # Replace placeholders with secrets and variables
  - task: FileTransform@1
    displayName: 'File transformation: ${{ parameters.appsettings }}'
    inputs:
      folderPath: ''
      targetFiles: '**/${{ parameters.appsettings }}'
      fileType: json
