parameters:
  # Tell the task to skip completely, for unsupported agents
  - name: skip
    type: boolean
    default: false
    
  # For samples that have no code Polaris is capable of scanning
  - name: skipPolaris
    type: boolean
    default: false
  
  # Tell the task to use Python requirements.txt for BlackDuck
  - name: useRequirementsTxt
    type: boolean
    default: false
  
  # Tell the task to use a specific path to the project
  - name: projectPath
    type: string
    default: ''
    
  # Build steps run ahead of the analysis jobs
  - name: buildSteps
    type: stepList
    default: []


jobs:   

- job: SynopsysPolarisScan
  timeoutInMinutes: 180
  pool:
      name: DevOps Managed AKS Admin
  steps:
  - ${{ parameters.buildSteps }}
  
  - powershell: |
      echo "##vso[task.setvariable variable=POLARIS_PROJECT_NAME]$(analysisProject)"
    displayName: Set POLARIS_PROJECT_NAME
  - task: blackduck.blackduck-coverity-on-polaris.blackduck-coverity-on-polaris-task.BlackduckCoverityOnPolaris@2
    displayName: Polaris Analyze
    inputs:
      polarisCommand: --configuration-file polaris.yml analyze --wait
      polarisService: 'PolarisScanner'
      waitForIssues: true
    condition: and(succeeded(), eq(${{ parameters.skip }}, false), eq(${{ parameters.skipPolaris }}, false))

  - template: "Pipelines/Templates/BlackDuck/v3/BlackDuckScanTemplate.step.v3.yml@ArchitectureRepo"
    parameters:
      projectName: product-readiness.$(analysisProject)
      projectVersionName: "$(Build.SourceBranchName)"
      blackDuckServiceConnection: 'BlackDuckScanner'
  

