# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- dev

pool:
  name: MPIBLDQ

steps:
- script: |
    python -m pip install --upgrade pip
    pip install requests
    pip install requests_kerberos
  displayName: 'Install dependencies'

- script: |
    python run_all_tests.py > output.txt 2>&1
  displayName: 'run all tests'
  workingDirectory: Python\
  continueOnError: 'true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Python\\output.txt'
    ArtifactName: 'results'
    publishLocation: 'Container'
