# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- dev

pool:
  name: MPIBLDQ

steps:
- script: |
  python -m pip install --upgrade pip
  pip install requests
  pip install requests_kerberos
  pip install unittest
  pip install unittest-xml-reporting
  displayName: 'Install dependencies'

- script: |
  python run_all_tests.py 2>&1
  workingDirectory: $(Build.SourcesDirectory)\Python
  continueOnError: 'true'
  displayName: 'Run Python tests'
  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**\output.xml'
    searchFolder: $(Build.SourcesDirectory)\Python
    testRunTitle: 'Publish Python test results'
